[theme]
# Primary accent colot for interactive elements.
primaryColor = "#AC6D74"

# Background color for the main content area.
backgroundColor = "#262626"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#586e75"